### PR TITLE
changes to run against version=4 models

### PR DESCRIPTION
**Pull request by klonikar**
Using the instructions to install and run in a docker container, I was not able to run the sample shell scripts.

Also, for the vehicle-attributes-recognition-barrier-0039.json, the json array of vehicles labels was a single string instead of json array.

### CODE REVIEW

**Comment by umed** [comment]
Hi @klonikar ,

Can you align with our master? We just uploaded new changes and there are some conflicts.

**Comment by klonikar** [comment]
Resolved. But merge this pull request *only if* your new changes do not support models version > 4. I had to make these changes as the docker created could not support models with version=6.

**Comment by klonikar** [comment]
Hi @umed ,

Can you merge or close this pull request? Its a small change for downloading and running version 4 models as the docker image created using [instructions to create docker image](https://github.com/opencv/gst-video-analytics/wiki/Getting-Started-Guide-%5BR2%5D#install-in-docker-image) does not install openvino version capable of running version 6 models.
But if you have updated the instructions or going to do so, please close the pull request.
Kiran

**Comment by umed** [comment]
hi @klonikar ,

We migrated to latest version of OpenVINO. Probably, it supports latest version of models.
By the way, don't see reasons to hardcode models version in `scripts/path_extractor.sh`.

**Comment by klonikar** [comment]
hi @umed ,

Thats fine. Hopefully the version of openvino that your new Dockerfile and build script installs does support latest version models.

I too did not want to hardcode  model version in scripts/path_extractor.sh but did that only after finding that higher version models are not supported by the openvino installed in the docker.

**Comment by umed** [comment]
Anyway, thank you @klonikar for your efforts! You are welcome to come with new contributions!

**Pull request closed without merging**
